# Generated by Django 4.2.11 on 2024-03-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('Staff', 'Staff'), ('User', 'User')], default='User', max_length=100, null=True),
        ),
    ]
